version: "3"
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: compasso-rabbit
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports: 
      - 5672:5672
      - 9191:15672
    networks: 
      - compasso
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9191"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express
    environment:
      #ME_CONFIG_BASICAUTH_USERNAME: root
      #ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    ports:
      - 8081:8081
    networks:
      - compasso

  mongo:
    image: mongo
    environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./mongodb/data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - compasso

  consumer:
    build: ./consumer
    container_name: consumer
    links:
      - rabbitmq
      - mongo
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI:mongodb://mongo:27017/compasso_db
      - SPRING_RABBITMQ_HOST:rabbitmq
      - SPRING_RABBITMQ_PORT:5672
      - SPRING_RABBITMQ_USERNAME:guest
      - SPRING_RABBITMQ_PASSWORD:guest
    ports:
      - 9090:9090
    networks: 
      - compasso

  producer:
    build: ./producer
    container_name: producer
    links:
      - rabbitmq
    depends_on: 
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST:rabbitmq
      - SPRING_RABBITMQ_PORT:5672
      - SPRING_RABBITMQ_USERNAME:guest
      - SPRING_RABBITMQ_PASSWORD:guest
    ports: 
      - 8080:8080
    networks: 
      - compasso

networks: 
  compasso: 
    driver: bridge